### PR TITLE
fix: add types to package exports

### PR DESCRIPTION
**Pull request by giovannipiller**
Ensures that the library can be used on TypeScript with `"moduleResolution": "bundler"`

### CODE REVIEW

**Comment by okikio** [comment]
I've released a change that should fix this issues and a couple others https://github.com/okikio/sharedworker/releases/tag/v1.0.5

**Comment by giovannipiller** [comment]
Thank you, however I don't think 1.0.5 got published to NPM.

https://www.npmjs.com/package/@okikio/sharedworker

**Comment by okikio** [comment]
It has now been fixed sorry about that 😓 
CleanShot 2023-12-13 at 17 05 28@2x

**Comment by giovannipiller** [comment]
Works great, thank you!

**Pull request closed without merging**
